
#ifndef INTERFACE_PLUGIN_EXPORT_H
#define INTERFACE_PLUGIN_EXPORT_H

#ifdef INTERFACE_PLUGIN_STATIC_DEFINE
#  define INTERFACE_PLUGIN_EXPORT
#  define INTERFACE_PLUGIN_NO_EXPORT
#else
#  ifndef INTERFACE_PLUGIN_EXPORT
#    ifdef interface_plugin_EXPORTS
        /* We are building this library */
#      define INTERFACE_PLUGIN_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define INTERFACE_PLUGIN_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef INTERFACE_PLUGIN_NO_EXPORT
#    define INTERFACE_PLUGIN_NO_EXPORT 
#  endif
#endif

#ifndef INTERFACE_PLUGIN_DEPRECATED
#  define INTERFACE_PLUGIN_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef INTERFACE_PLUGIN_DEPRECATED_EXPORT
#  define INTERFACE_PLUGIN_DEPRECATED_EXPORT INTERFACE_PLUGIN_EXPORT INTERFACE_PLUGIN_DEPRECATED
#endif

#ifndef INTERFACE_PLUGIN_DEPRECATED_NO_EXPORT
#  define INTERFACE_PLUGIN_DEPRECATED_NO_EXPORT INTERFACE_PLUGIN_NO_EXPORT INTERFACE_PLUGIN_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef INTERFACE_PLUGIN_NO_DEPRECATED
#    define INTERFACE_PLUGIN_NO_DEPRECATED
#  endif
#endif

#endif /* INTERFACE_PLUGIN_EXPORT_H */
